---
- name: Install cert-manager operator
  redhat.openshift.k8s:
    state: present
    src: "cert-manager-operator.yml"

- name: Wait till the Object is created
  kubernetes.core.k8s_info:
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    wait: true
    name: cert-manager-operator
    namespace: cert-manager-operator
    wait_sleep: 10
    wait_timeout: 360
